import Catch from './functional-error-boundary';

export default Catch;
